ProyectoFinal/FrontEnd/Models/CarritoViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FrontEnd.Models
{
    // clase utilizada para obtener todos los datos de productos para el Index.html
    public class IndexCarritoViewModels
    {
        [Required]
        [Key]
        [Display(Name = "Codigo")]
        public int Id_Producto { get; set; }

        [Required]
        [Display(Name = "Producto")]
        public string Nombre { get; set; }

        [Required]
        [Display(Name = "Precio")]
        public double? Precio { get; set; }

        [Required]
        [Display(Name = "Modelo")]
        public string Modelo { get; set; }

        [Required]
        [Display(Name = "Cantidad")]
        public int? cantidad { get; set; }

        [Required]
        [Display(Name = "Marca")]
        public string marca { get; set; }

        [Required]
        [Display(Name = "Agregado")]
        public DateTime fecha_agregado { get; set; }

        [Required]
        [Display(Name = "Ultima modificacion")]
        public DateTime fecha_modificado { get; set; }
    }

    public class EditarCarritoViewModel
    {
        [Required]
        [Key]
        [Display(Name = "Codigo")]
        public int Id_Producto { get; set; }

        [Required]
        [Display(Name = "Cantidad")]
        public int? cantidad { get; set; }
    }
}

ProyectoFinal/FrontEnd/Controllers/User/CarritoController.cs
using BackEnd.DAL;
using BackEnd.Entities;
using FrontEnd.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FrontEnd.Controllers.User
{
    [CustomAuthorize(Roles = "Usuario")]
    public class CarritoController : Controller
    {
        private UnidadDeTrabajo<carrito> unidad_carrito = new UnidadDeTrabajo<carrito>(new BDContext());
        private UnidadDeTrabajo<usuarios> unidad_usuario = new UnidadDeTrabajo<usuarios>(new BDContext());
        private UnidadDeTrabajo<marcas> unidad_marcas = new UnidadDeTrabajo<marcas>(new BDContext());
        private UnidadDeTrabajo<productos> unidad_productos = new UnidadDeTrabajo<productos>(new BDContext());

        // GET: Carrito
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Usuario")) 
            {
                BDContext context = new BDContext();

                // obtener el id del usuario que esta logueado
                var userID = User.Identity.GetUserId();

                // obtener el usuario con ese id de base de datos
                var usuario_BD = context.usuarios.Where(u => u.Usuario_ID.Equals(userID)).Single();
                
                // obtener todos los productos en su carrito
                List<sp_obtenerProductosUsuarioCarrito_Result> lista_productos_cliente = context.sp_obtenerProductosUsuarioCarrito(usuario_BD.userId).ToList();
                
                // obtener todos los demas datos necesarios
                List<marcas> lista_marcas = unidad_marcas.genericDAL.GetAll().ToList();
                List<IndexCarritoViewModels> lista_productos_VM = new List<IndexCarritoViewModels>();
                productos producto_BD;
                IndexCarritoViewModels producto_VM;

                // asignar valores correspondientes
                foreach (var producto in lista_productos_cliente)
                {
                    producto_BD = unidad_productos.genericDAL.Get(producto.productoId);

                    // no tomar en cuenta los productos con estado bloqueado
                    if (producto_BD.id_estado == 1)
                    {
                        continue;
                    }
                    else
                    {
                        foreach (var marca in lista_marcas)
                        {
                            if (marca.id_marca == producto_BD.id_marca)
                            {
                                producto_VM = new IndexCarritoViewModels()
                                {
                                    Id_Producto = producto_BD.productoId,
                                    Nombre = producto_BD.nombre,
                                    Precio = producto_BD.precio,
                                    Modelo = producto_BD.modelo,
                                    cantidad = producto.cantidad_producto,
                                    marca = marca.nombre
                                };
                                lista_productos_VM.Add(producto_VM);
                                break;
                            }
                        }
                    }
                }
                return View("~/Views/User/Carrito/Index.cshtml", lista_productos_VM);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
        }

        // POST: HomeAdmin/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Agregar(DetallesProductoViewModels productoVM)
        {
            BDContext context = new BDContext();

            try
            {
                // obtener el id del usuario que esta logueado
                var userID = User.Identity.GetUserId();

                // obtener el usuario con ese id de base de datos
                var usuario_BD = context.usuarios.Where(u => u.Usuario_ID.Equals(userID)).Single();

                // obtener productos del carrito del usuario
                List<sp_obtenerProductosUsuarioCarrito_Result> lista_productos_cliente = context.sp_obtenerProductosUsuarioCarrito(usuario_BD.userId).ToList();

                // verificar si el usuario ya tiene ese producto en el carrito
                foreach(var producto in lista_productos_cliente)
                {
                    if(producto.productoId == productoVM.Id_Producto)
                    {
                        // usuario ya tiene ese producto en el carrito, preguntar si desea modificar
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                }

                // crear el producto que se va a agregar al carrito
                carrito producto_carrito = new carrito
                {
                    productoId = productoVM.Id_Producto,
                    userId = usuario_BD.userId,
                    cantidad_producto = (int)productoVM.cantidad,
                    fecha_agregado = DateTime.UtcNow,
                    fecha_modificado = DateTime.UtcNow
                };

                unidad_carrito.genericDAL.Add(producto_carrito);
                unidad_carrito.Complete();
                
                // devolver http 200
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            catch (Exception)
            {
                // error, devolver http 500
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        public ActionResult Editar(int? id)
        {
            if(id == null || id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            
            try
            {

                id = (int)id;
                BDContext context = new BDContext();

                // obtener el id del usuario que esta logueado
                var userID = User.Identity.GetUserId();

                // obtener el usuario con ese id de base de datos
                var usuario_BD = context.usuarios.Where(u => u.Usuario_ID.Equals(userID)).Single();

                // obtener productos del carrito del usuario
                List<sp_obtenerProductosUsuarioCarrito_Result> lista_productos_cliente = context.sp_obtenerProductosUsuarioCarrito(usuario_BD.userId).ToList();

                EditarCarritoViewModel productoVM = null;

                foreach (var producto in lista_productos_cliente)
                {
                    if(producto.productoId == id)
                    {
                        productoVM = new EditarCarritoViewModel
                        {
                            Id_Producto = producto.productoId,
                            cantidad = producto.cantidad_producto
                        };
                        break;
                    }
                }

                if(productoVM == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.NotFound);
                }

                return View("~/Views/User/Carrito/Editar.cshtml", productoVM);
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(int? Id_Producto, int? cantidad_producto)
        {
            try
            {
                BDContext context = new BDContext();

                // obtener el id del usuario que esta logueado
                var userID = User.Identity.GetUserId();

                // obtener el usuario con ese id de base de datos
                var usuario_BD = context.usuarios.Where(u => u.Usuario_ID.Equals(userID)).Single();

                carrito carrito = new carrito
                {
                    productoId = (int)Id_Producto,
                    userId = usuario_BD.userId,
                    cantidad_producto = (int)cantidad_producto,
                    fecha_modificado = DateTime.UtcNow
                };

                unidad_carrito.genericDAL.Update(carrito);
                unidad_carrito.Complete();
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        // POST: Carrito/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            // revisar si el URL contiene un ID, si no entonces devolver 404
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            BDContext context = new BDContext();

            // obtener el id del usuario que esta logueado
            var userID = User.Identity.GetUserId();

            // obtener el usuario con ese id de base de datos
            var usuario_BD = context.usuarios.Where(u => u.Usuario_ID.Equals(userID)).Single();

            // eliminar producto con el procedimiento almacenado
            context.sp_eliminarProductoCarrito(id, usuario_BD.userId);

            // devolver que todo bien
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

    }
}

ProyectoFinal/FrontEnd/Controllers/User/ProductosController.cs
using BackEnd.DAL;
using BackEnd.Entities;
using FrontEnd.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FrontEnd.Controllers.User
{
    public class ProductosController : Controller
    {

        // unidades de trabajo para obtener datos necesarios
        private UnidadDeTrabajo<productos> unidad_productos = new UnidadDeTrabajo<productos>(new BDContext());
        private UnidadDeTrabajo<categorias> unidad_categorias = new UnidadDeTrabajo<categorias>(new BDContext());
        private UnidadDeTrabajo<marcas> unidad_marcas = new UnidadDeTrabajo<marcas>(new BDContext());
        private UnidadDeTrabajo<colecciones> unidad_colecciones = new UnidadDeTrabajo<colecciones>(new BDContext());
        private UnidadDeTrabajo<distribuidor> unidad_distribuidor = new UnidadDeTrabajo<distribuidor>(new BDContext());

        // GET: Productos
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        // GET: Productos/Detalles/5
        public ActionResult Detalles(int? id)
        {
            // revisar si el URL contiene un ID, si no entonces devolver 404
            if (id == null || id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // buscar el producto y los demas datos
            productos producto = unidad_productos.genericDAL.Get((int)id);
            marcas marca = unidad_marcas.genericDAL.Get((int)producto.id_marca);
            colecciones coleccion = unidad_colecciones.genericDAL.Get((int)producto.id_coleccion);
            categorias categoria = unidad_categorias.genericDAL.Get((int)producto.id_categoria);
            distribuidor distribuidor = unidad_distribuidor.genericDAL.Get((int)producto.id_distribuidor);

            // ver si el producto tiene estado bloqueado. Si si, devolver 404
            if (producto.id_estado == 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // asignar datos al view model correspondiente
            DetallesProductoViewModels producto_VM = new DetallesProductoViewModels
            {
                Id_Producto = producto.productoId,
                Nombre = producto.nombre,
                Precio = producto.precio,
                Descripcion = producto.descripcion,
                Modelo = producto.modelo,
                marca = marca.nombre,
                coleccion = coleccion.nombre,
                categoria = categoria.nombre,
                distribuidor = distribuidor.nombre
            };

            return View(producto_VM);
        }
    }
}

ProyectoFinal/FrontEnd/Views/User/Carrito/Editar.cshtml
@model FrontEnd.Models.EditarCarritoViewModel

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>
<div class="form-horizontal">
    <h4>Cambiar cantidad</h4>
    <hr />
    <form id="__AjaxAntiForgeryForm" action="#" method="post"> @Html.AntiForgeryToken()</form>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id_Producto)

    <div class="form-group">
        @Html.LabelFor(m => m.cantidad)
        @Html.EditorFor(m => m.cantidad, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "1", @max = "5", @style = "background:black; color:white;" } })
        @Html.ValidationMessageFor(m => m.cantidad, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-sm" id="Guardar" onclick="guardar()">Guardar</button>
        @Html.ActionLink("Volver", "Index", "Carrito", htmlAttributes: new { @class = "btn btn-primary btn-sm" })
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function guardar() {
            var saveUrl = '@Url.Action("Editar", "Carrito")';
            var carritoUrl = '@Url.Action("Index", "Carrito")';
            var indexUrl = '@Url.Action("Index", "Home")';
            var Id_Producto = $("#Id_Producto").val();
            var cantidad_producto = $("#cantidad").val();
            $.ajax({
                type: 'POST',
                url: saveUrl,
                data: {
                    __RequestVerificationToken: $('[name = "__RequestVerificationToken"]').val(),
                    Id_Producto: Id_Producto,
                    cantidad_producto: cantidad_producto,
                },
                statusCode: {
                    200: function () {
                        Swal.fire({
                            title: 'Editado!',
                            text: "El producto ha sido editado con exito!",
                            type: 'success',
                            showCancelButton: true,
                            confirmButtonColor: '#3085d6',
                            cancelButtonColor: '#3085d6',
                            confirmButtonText: 'Seguir comprando',
                            cancelButtonText: 'Ir al carrito'
                        }).then((result) => {
                            if (result.value) {
                                window.location.href = indexUrl;
                            }
                            else {
                                window.location.href = carritoUrl;
                            }
                        })
                    },
                    404: function () {
                        Swal.fire(
                            'Error!',
                            'Pagina no encontrada',
                            'error'
                        ).then(function () {
                            location.reload();
                        });
                    },
                    500: function () {
                        Swal.fire(
                            'Error!',
                            'Lo sentimos, hubo un error. Por favor intentelo de nuevo mas tarde',
                            'error'
                        ).then(function () {
                            window.location.href = saveUrl;
                        });
                    }
                }
            });
        }
    </script>
}

ProyectoFinal/FrontEnd/Views/User/Carrito/Index.cshtml
@model IEnumerable<FrontEnd.Models.IndexCarritoViewModels>
@{
    /**/

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Productos en carrito</h2>
<hr />
<section style="float: left; margin: 0 1.5%; width: 61%;">
    <div class="row">
        @{
            if (Model.Count() > 0)
            {
                foreach (var producto in Model)
                {
                    <div class="col-lg-6 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    @producto.Nombre
                                </h4>
                                <h6>$@producto.Precio</h6>
                                <h6>Cantidad en carrito: @producto.cantidad</h6>
                            </div>
                            <div class="card-footer">
                                @Html.ActionLink("Detalles", "Detalles", "Productos", new { id = producto.Id_Producto }, new { @class = "btn btn-primary btn-sm" })
                                @Html.ActionLink("Editar", "Editar", "Carrito", new { id = producto.Id_Producto }, new { @class = "btn btn-primary btn-sm" })
                                <button type="button" class="btn btn-primary btn-sm" onclick="eliminar(@producto.Id_Producto)">Eliminar</button>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="col-lg-12 col-md-12">
                    <h5>Aun no hay productos en su carrito. Dirijase a comprar!</h5>
                </div>
                <div class="col-lg-12 col-md-12">
                    @Html.ActionLink("Comprar", "Index", "Home", null, new { @class = "btn btn-primary btn-sm" })
                </div>
            }
        }
    </div>
</section>
@{
    if (Model.Count() > 0)
    {
        <aside style="float: right; margin: 0 1.5%; width: 30%;">
            @{
                double total = 0;
                double subtotal = 0;
                foreach (var producto in Model)
                {
                    total += (double)(producto.cantidad * producto.Precio);
                }
                <h6>Total: </h6>
                <p>$@total</p>
                <h6>Impuestos: </h6>
                <p>13%</p>
                <h6>Subtotal: </h6>
                subtotal = total + (total * 0.13);
                <p>$@subtotal</p>
            }
            @Html.ActionLink("Finalizar compra", "Index", "Compra", null, new { @class = "btn btn-primary pull-right" })
        </aside>

    }
}

@section Scripts
{
    <script>
        $("#carritoTabla").DataTable({
            responsive: true,
            "destroy": true,
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
            }
        });

        function eliminar(id_producto) {
            Swal.fire({
                title: 'Seguro que desea eliminar este producto del carrito?',
                text: "Esta accion no se puede revertir!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Eliminar'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: 'POST',
                        url: `Carrito/Delete/${id_producto}`,
                        data: {
                            id_producto: id_producto
                        },
                        statusCode: {
                            200: function () {
                                Swal.fire(
                                    'Exito!',
                                    'Producto eliminado',
                                    'success'
                                ).then(function () {
                                    location.reload();
                                });
                            },
                            400: function () {
                                Swal.fire(
                                    'Error!',
                                    'Bad request',
                                    'error'
                                ).then(function () {
                                    location.reload();
                                });
                            },
                            404: function () {
                                Swal.fire(
                                    'Error!',
                                    'Pagina no encontrada',
                                    'error'
                                ).then(function () {
                                    location.reload();
                                });
                            },
                            500: function () {
                                Swal.fire(
                                    'Error!',
                                    'Lo sentimos, hubo un error. Por favor intentelo de nuevo mas tarde',
                                    'error'
                                ).then(function () {
                                    location.reload();
                                });
                            }
                        }

                    });
                }
            })
        }
    </script>
}