ProyectoFinal/FrontEnd/Controllers/Admin/MarcasAdminController.cs
using BackEnd.DAL;
using BackEnd.Entities;
using FrontEnd.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FrontEnd.Controllers.Admin
{
    [CustomAuthorize(Roles = "Admin")]
    public class MarcasAdminController : Controller
    {
        // GET: MarcasAdmin
        public ActionResult Index()
        {
           
            List<marcas> marcas;
            using (UnidadDeTrabajo<marcas> unidad = new UnidadDeTrabajo<marcas>(new BDContext()))
            {
                marcas = unidad.genericDAL.GetAll().ToList();
            }

            List<MarcasViewModel> marcasVM = new List<MarcasViewModel>();
            MarcasViewModel marcaVM;

            foreach (var item in marcas)
            {
                if (item.id_estado == 1)
                {
                    continue;
                }
                else
                {
                    marcaVM = new MarcasViewModel
                    {
                        id_marca = item.id_marca,
                        nombre = item.nombre,
                        descripcion = item.descripcion
                    };
                    marcasVM.Add(marcaVM);
                }
            
            }
            return View("~/Views/Admin/MarcasAdmin/Index.cshtml", marcasVM);
        }

        // GET: CategoriasAdmin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CategoriasAdmin/Create
        public ActionResult Create()
        {
            return View("~/Views/Admin/MarcasAdmin/Create.cshtml");
        }

        // POST: CategoriasAdmin/Create
        [HttpPost]
        public ActionResult Create(MarcasViewModel marcaVM)
        {
            try
            {
                // TODO: Add insert logic here
                marcas marca = new marcas
                {
                    nombre = marcaVM.nombre,
                    descripcion = marcaVM.descripcion,
                    id_estado = 2
                };

                if (marca.nombre != null)
                {
                    using (UnidadDeTrabajo<marcas> unidad = new UnidadDeTrabajo<marcas>(new BDContext()))
                    {
                        unidad.genericDAL.Add(marca);
                        unidad.Complete();
                    }
                    return new HttpStatusCodeResult(HttpStatusCode.OK);
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
                }
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        // GET: MarcasAdmin/Edit/5
        public ActionResult Edit(int id)
        {
            // revisar si el URL contiene un ID, si no entonces devolver 404
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            MarcasViewModel marcasViewModel;
            marcas marca;
            using (UnidadDeTrabajo<marcas> unidad = new UnidadDeTrabajo<marcas>(new BDContext()))
            {
                marca = unidad.genericDAL.Get(id);
            }
            if (marca.id_estado == 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            marcasViewModel = new MarcasViewModel
            {
                id_marca = marca.id_marca,
                nombre = marca.nombre,
                descripcion = marca.descripcion,
            };

            return View("~/Views/Admin/MarcasAdmin/Edit.cshtml", marcasViewModel);
        }

        // POST: CategoriasAdmin/Edit/5
        [HttpPost]
        public ActionResult Edit(MarcasViewModel marcasViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (UnidadDeTrabajo<marcas> unidad = new UnidadDeTrabajo<marcas>(new BDContext()))
                    {
                        marcas marca = new marcas
                        {
                            id_marca = marcasViewModel.id_marca,
                            nombre = marcasViewModel.nombre,
                            descripcion = marcasViewModel.descripcion

                        };

                        unidad.genericDAL.Update(marca);
                        unidad.Complete();
                        return new HttpStatusCodeResult(HttpStatusCode.OK);
                    }
                }
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);

            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

       
        // POST: MarcasAdmin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            // revisar si el URL contiene un ID, si no entonces devolver 404
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            marcas marca = new marcas();
            using (UnidadDeTrabajo<marcas> unidad_marca = new UnidadDeTrabajo<marcas>(new BDContext()))
            {
                // buscar el producto y los demas datos
                marca = unidad_marca.genericDAL.Get(id);
                marca.id_estado = 1;

            }

            using (UnidadDeTrabajo<marcas> unidad_marca = new UnidadDeTrabajo<marcas>(new BDContext()))
            {
                unidad_marca.genericDAL.Update(marca);
                unidad_marca.Complete();
            }
            // devolver que todo bien
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
    }
}

ProyectoFinal/FrontEnd/Views/Admin/MarcasAdmin/Create.cshtml
@model FrontEnd.Models.MarcasViewModel

@{
    ViewBag.Title = "Agregar Marca";
}

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Agregar Marca</h3>
    </div>
    <div class="box-body">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <form id="__AjaxAntiForgeryForm" action="#" method="post"> @Html.AntiForgeryToken()</form>
        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.ActionLink("Volver", "Index", routeValues: null, htmlAttributes: new { @class = "btn btn-primary" })
            <button type="submit" class="btn btn-primary" id="Guardar" onclick="guardar()">Guardar</button>
        </div>
    </div>
</div>


@section Scripts
{
    <script>
        function guardar() {
            var saveUrl = '@Url.Action("Create", "MarcasAdmin")';
            var newUrl = '@Url.Action("Index", "MarcasAdmin")';
            $.ajax({
                type: 'POST',
                url: saveUrl,
                data: {
                    __RequestVerificationToken: $('[name = "__RequestVerificationToken"]').val(),
                    nombre: $("#nombre").val(),
                    descripcion: $("#descripcion").val(),
                },
                statusCode: {
                    200: function () {
                        Swal.fire(
                            'Marca agregado!',
                            'La Marca ha sido agregado exitosamente!',
                            'success'
                        ).then(function () {
                            window.location.href = newUrl;
                        });
                    },
                    400: function () {
                        Swal.fire(
                            'Error!',
                            'Bad request',
                            'error'
                        ).then(function () {
                            location.reload();
                        });
                    },
                    404: function () {
                        Swal.fire(
                            'Error!',
                            'Pagina no encontrada',
                            'error'
                        ).then(function () {
                            location.reload();
                        });
                    },
                    500: function () {
                        Swal.fire(
                            'Error!',
                            'Lo sentimos, hubo un error. Por favor intentelo de nuevo mas tarde',
                            'error'
                        ).then(function () {
                            location.reload();
                        });
                    }
                }

            });
        }
    </script>
}

ProyectoFinal/FrontEnd/Views/Admin/MarcasAdmin/Delete.cshtml
@model FrontEnd.Models.MarcasViewModel

@{
    ViewBag.Title = "Eliminar Marca";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Eliminar Marcas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProyectoFinal/FrontEnd/Views/Admin/MarcasAdmin/Edit.cshtml
@model FrontEnd.Models.MarcasViewModel

@{

    ViewBag.Title = "Editar Marca";

}

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Editar Categoria @Model.nombre</h3>
    </div>


    <div class="box-body">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <form id="__AjaxAntiForgeryForm" action="#" method="post"> @Html.AntiForgeryToken()</form>
        @Html.HiddenFor(marca => marca.id_marca, new { id = "id_marca" })

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
        </div>

        <!-- /.box-body -->
        <div class="box-footer">
            @Html.ActionLink("Volver", "Index", routeValues: null, htmlAttributes: new { @class = "btn btn-primary" })
            <button type="submit" class="btn btn-primary" id="Guardar" onclick="guardar()">Guardar</button>
        </div>
    </div>
 </div>

@section Scripts
{
    <script>
        function guardar() {
            var saveUrl = '@Url.Action("Edit", "MarcasAdmin")';
            var newUrl = '@Url.Action("Index", "MarcasAdmin")';
            $.ajax({
                type: 'POST',
                url: saveUrl,
                data: {
                    __RequestVerificationToken: $('[name = "__RequestVerificationToken"]').val(),
                    id_marca: $("#id_marca").val(),
                    nombre: $("#nombre").val(),
                    descripcion: $("#descripcion").val(),
                },
                statusCode: {
                    200: function () {
                        Swal.fire(
                            'Marca editado!',
                            'La Marca ha sido editado exitosamente!',
                            'success'
                        ).then(function () {
                            window.location.href = newUrl;
                        });
                    },
                    400: function () {
                        Swal.fire(
                            'Error!',
                            'Bad request',
                            'error'
                        ).then(function () {
                            location.reload();
                        });
                    },
                    404: function () {
                        Swal.fire(
                            'Error!',
                            'Pagina no encontrada',
                            'error'
                        ).then(function () {
                            location.reload();
                        });
                    },
                    500: function () {
                        Swal.fire(
                            'Error!',
                            'Lo sentimos, hubo un error. Por favor intentelo de nuevo mas tarde',
                            'error'
                        ).then(function () {
                            location.reload();
                        });
                    }
                }
            });
         }
</script>
 }

ProyectoFinal/FrontEnd/Views/Admin/MarcasAdmin/Index.cshtml
@model IEnumerable<FrontEnd.Models.MarcasViewModel>

@{
    ViewBag.Title = "Index";

}
<div class="btn-group">
    @Html.ActionLink("Agregar Nueva Marca", "Create", null, new { @class = "btn btn-block btn-success" })
    <br><br><br>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="box">

            <div class="box-header">
                <h2 class="box-title">Marcas</h2>
            </div>

            <div class="box-body table-responsive">
                <table id="marcaTabla" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.nombre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.descripcion)
                            </th>
                            <th>Acciones</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.descripcion)
                                </td>
                                <td>
                                    @Html.ActionLink("Editar", "Edit", new { id = item.id_marca }, new { @class = "btn btn-warning" })
                                    <button type="button" class="btn btn-danger" onclick="eliminar(@item.id_marca)">Eliminar</button>
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>

        $(document).ready(function () {
            $("#marcaTabla").DataTable({
                responsive: true,
                "destroy": true,
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                }
            });
        });

        function eliminar(id_marca) {
            Swal.fire({
                title: 'Seguro que desea eliminar esta Marca?',
                text: "Esta accion no se puede revertir!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Eliminar'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: 'POST',
                        url: `MarcasAdmin/Delete/${id_marca}`,
                        data: {
                            id_marca: id_marca
                        },
                        statusCode: {
                            200: function () {
                                Swal.fire(
                                    'Exito!',
                                    'Marca eliminado',
                                    'success'
                                ).then(function () {
                                    location.reload();
                                });
                            },
                            400: function () {
                                Swal.fire(
                                    'Error!',
                                    'Bad request',
                                    'error'
                                ).then(function () {
                                    location.reload();
                                });
                            },
                            404: function () {
                                Swal.fire(
                                    'Error!',
                                    'Pagina no encontrada',
                                    'error'
                                ).then(function () {
                                    location.reload();
                                });
                            },
                            500: function () {
                                Swal.fire(
                                    'Error!',
                                    'Lo sentimos, hubo un error. Por favor intentelo de nuevo mas tarde',
                                    'error'
                                ).then(function () {
                                    location.reload();
                                });
                            }
                        }

                    });
                }
            })
        }

    </script>

}