ProyectoFinal/FrontEnd/Models/Admin/CategoriasAdminViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FrontEnd.Models.Admin
{
    public class CategoriasAdminViewModel
    {
        [Key]
        [Display(Name = "Id")]
        public int id_categoria { get; set; }

        [Display(Name = "Nombre")]
        [Required]
        public string nombre { get; set; }

        [Display(Name = "Descripcion")]
        public string descripcion { get; set; }
    }
}

ProyectoFinal/FrontEnd/Controllers/Admin/CategoriasAdminController.cs
using BackEnd.DAL;
using BackEnd.Entities;
using FrontEnd.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FrontEnd.Controllers.Admin
{
    [CustomAuthorize(Roles = "Admin")]
    public class CategoriasAdminController : Controller
    {

        private UnidadDeTrabajo<categorias> unidad_categorias = new UnidadDeTrabajo<categorias>(new BDContext());

        // GET: CategoriasAdmin
        public ActionResult Index()
        {
            List<categorias> categorias;
            using (UnidadDeTrabajo<categorias> unidad = new UnidadDeTrabajo<categorias>(new BDContext()))
            {
                categorias = unidad.genericDAL.GetAll().ToList();
            }
         
            List<CategoriasViewModel> categoriasVM = new List<CategoriasViewModel>();
            CategoriasViewModel categoriaVM;
            

            
            foreach (var item in categorias)
            {
                if (item.id_estado == 1)
                {
                    continue;
                }
                else
                {

                    categoriaVM = new CategoriasViewModel
                    {
                        id_categoria = item.id_categoria,
                        nombre = item.nombre,
                        descripcion = item.descripcion
                    };
                    categoriasVM.Add(categoriaVM);
                    
                }
                
            }
            return View("~/Views/Admin/CategoriasAdmin/Index.cshtml", categoriasVM);
        }

        // GET: CategoriasAdmin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CategoriasAdmin/Create
        public ActionResult Create()
        {
            
            
            return View("~/Views/Admin/CategoriasAdmin/Create.cshtml");
        }

        // POST: CategoriasAdmin/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoriasViewModel categoriaVM)
        {
            try
            {
                // TODO: Add insert logic here
                categorias categoria = new categorias
                {
                    nombre = categoriaVM.nombre,
                    descripcion = categoriaVM.descripcion,
                    id_estado = 2
                };
                if (categoria.nombre != null)
                {
                    using (UnidadDeTrabajo<categorias> unidad = new UnidadDeTrabajo<categorias>(new BDContext()))
                    {
                        unidad.genericDAL.Add(categoria);
                        unidad.Complete();
                    }
                    return new HttpStatusCodeResult(HttpStatusCode.OK);
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
                }
                

               
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        // GET: CategoriasAdmin/Edit/5
        public ActionResult Edit(int id)
        {
            // revisar si el URL contiene un ID, si no entonces devolver 404
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriasViewModel categoriasViewModel;
            categorias categoria;

            // ver si el producto tiene estado bloqueado. Si si, devolver 404
            


            using (UnidadDeTrabajo<categorias> unidad = new UnidadDeTrabajo<categorias>(new BDContext()))
            {
                categoria = unidad.genericDAL.Get(id);
            }

            if (categoria.id_estado == 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            categoriasViewModel = new CategoriasViewModel {
                id_categoria = categoria.id_categoria,
                nombre = categoria.nombre,
                descripcion = categoria.descripcion,
                id_estado = 2
            };

            
            return View("~/Views/Admin/CategoriasAdmin/Edit.cshtml", categoriasViewModel);
        }

        // POST: CategoriasAdmin/Edit/5
        [HttpPost]
        public ActionResult Edit(CategoriasViewModel categoriasViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (UnidadDeTrabajo<categorias> unidad = new UnidadDeTrabajo<categorias>(new BDContext()))
                    {
                        categorias categoria = new categorias
                        {
                            id_categoria = categoriasViewModel.id_categoria,
                            nombre = categoriasViewModel.nombre,
                            descripcion = categoriasViewModel.descripcion,
                            id_estado = 2
                            
                        };

                        unidad.genericDAL.Update(categoria);
                        unidad.Complete();
                    }
                    return new HttpStatusCodeResult(HttpStatusCode.OK);
                }


                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        // POST: CategoriasAdmin/Delete/5
        [HttpPost]
        public ActionResult Delete(int? id)
        {
            // revisar si el URL contiene un ID, si no entonces devolver 404
            if (id == 0 || id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // buscar la categoria y los demas datos
            categorias categoria = unidad_categorias.genericDAL.Get((int)id);
            categoria.id_estado = 1;
            unidad_categorias.genericDAL.Update(categoria);
            unidad_categorias.Complete();

            // devolver que todo bien
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

    }
}

ProyectoFinal/FrontEnd/Views/Admin/CategoriasAdmin/Create.cshtml
@model FrontEnd.Models.CategoriasViewModel

@{
    ViewBag.Title = "Create";
}

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Agregar Categoria</h3>
    </div>
    <div class="box-body">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <form id="__AjaxAntiForgeryForm" action="#" method="post"> @Html.AntiForgeryToken()</form>
        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.ActionLink("Volver", "Index", routeValues: null, htmlAttributes: new { @class = "btn btn-primary" })
            <button type="submit" class="btn btn-primary" id="Guardar" onclick="guardar()">Guardar </button>
        </div>

    </div>

</div>

@section Scripts
{
    <script>
        function guardar() {
            var saveUrl = '@Url.Action("Create", "CategoriasAdmin")';
            var newUrl = '@Url.Action("Index"   , "CategoriasAdmin")';
            $.ajax({
                type: 'POST',
                url: saveUrl,
                data: {
                    __RequestVerificationToken: $('[name = "__RequestVerificationToken"]').val(),
                    nombre: $("#nombre").val(),
                    descripcion: $("#descripcion").val(),

                },
                statusCode: {
                    200: function () {
                        Swal.fire(
                            'Categoria agregado!',
                            'La Categoria ha sido agregado exitosamente!',
                            'success'
                        ).then(function () {
                            window.location.href = newUrl;
                        });
                    },
                    400: function () {
                        Swal.fire(
                            'Error!',
                            'Bad request',
                            'error'
                        ).then(function () {
                            location.reload();
                        });
                    },
                    404: function () {
                        Swal.fire(
                            'Error!',
                            'Pagina no encontrada',
                            'error'
                        ).then(function () {
                            location.reload();
                        });
                    },
                    500: function () {
                        Swal.fire(
                            'Error!',
                            'Lo sentimos, hubo un error. Por favor intentelo de nuevo mas tarde',
                            'error'
                        ).then(function () {
                            location.reload();
                        });
                    }
                }

            });
        }
    </script>
}

ProyectoFinal/FrontEnd/Views/Admin/CategoriasAdmin/Delete.cshtml
@model FrontEnd.Models.CategoriasViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CategoriasViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProyectoFinal/FrontEnd/Views/Admin/CategoriasAdmin/Edit.cshtml
@model FrontEnd.Models.CategoriasViewModel

@{

    ViewBag.Title = "Actualizar Categoria";

}

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Actualizar @Model.nombre</h3>
    </div>

    <div class="box-body">
       
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <form id="__AjaxAntiForgeryForm" action="#" method="post"> @Html.AntiForgeryToken()</form>
            @Html.HiddenFor(model => model.id_categoria, new { id = "id_categoria" })

            <div class="form-group">
                @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                </div>
            </div>

            <!-- /.box-body -->
            <div class="box-footer">
                @Html.ActionLink("Regresar", "Index")
                <button type="submit" class="btn btn-info pull-right" id="Guardar" onclick="guardar()">Editar</button>
            </div>
        </div>
        
    </div>

</div>



@section Scripts
{
    <script>
        function guardar() {
            var saveUrl = '@Url.Action("Edit", "CategoriasAdmin")';
            var newUrl = '@Url.Action("Index", "CategoriasAdmin")';
            $.ajax({
                type: 'POST',
                url: saveUrl,
                data: {
                    __RequestVerificationToken: $('[name = "__RequestVerificationToken"]').val(),
                    id_categoria: $("#id_categoria").val(),
                    nombre: $("#nombre").val(),
                    descripcion: $("#descripcion").val(),
                },
                statusCode: {
                    200: function () {
                        Swal.fire(
                            'Categoria editado!',
                            'La categoria ha sido editado exitosamente!',
                            'success'
                        )
                        setTimeout(function () {
                            window.location.href = newUrl;
                        }, 3000);

                    },
                    400: function () {
                        Swal.fire(
                            'Error!',
                            'Bad request',
                            'error'
                        )
                        setTimeout(function () {
                            location.reload();
                        }, 3000);

                    },
                    404: function () {
                        Swal.fire(
                            'Error!',
                            'Pagina no encontrada',
                            'error'
                        )
                        setTimeout(function () {
                            location.reload();
                        }, 3000);
                    },
                    500: function () {
                        Swal.fire(
                            'Error!',
                            'Lo sentimos, hubo un error. Por favor intentelo de nuevo mas tarde',
                            'error'
                        )
                        setTimeout(function () {
                            location.reload();
                        }, 3000);
                    }
                }

            });
        }
    </script>
}

ProyectoFinal/FrontEnd/Views/Admin/CategoriasAdmin/Index.cshtml
@model IEnumerable<FrontEnd.Models.CategoriasViewModel>

@{
    ViewBag.Title = "Index";

}
<div class="btn-group">
    @Html.ActionLink("Agregar Nueva Categoria", "Create", null, new { @class = "btn btn-block btn-success" })
    <br><br><br>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="box">

            <div class="box-header">
                <h2 class="box-title">Categorias</h2>
            </div>

            <div class="box-body table-responsive">
                <table id="tablaCategorias" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.id_categoria)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.nombre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.descripcion)
                            </th>
                            <th>Acciones</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.id_categoria)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.descripcion)
                            </td>
                            <td>
                                @Html.ActionLink("Editar", "Edit", new { id = item.id_categoria }, new { @class = "btn btn-warning" })
                                <button type="button" class="btn btn-danger" onclick="eliminar(@item.id_categoria)">Eliminar</button>
                            </td>
                        </tr>
                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            cargarTabla();
        });

        // funcion para cargar DataTable con información de historial
        var cargarTabla = function () {
            var tabla = $("#tablaCategorias").DataTable({
                responsive: true,
                "destroy": true,
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                }
            });
        }

        function eliminar(id_categoria) {
            Swal.fire({
                title: 'Seguro que desea eliminar esta categoria?',
                text: "Esta accion no se puede revertir!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Eliminar'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: 'POST',
                        url: `CategoriasAdmin/Delete/${id_categoria}`,
                        data: {
                            id_categoria: id_categoria
                        },
                        statusCode: {
                            200: function () {
                                Swal.fire(
                                    'Exito!',
                                    'Categoria eliminada',
                                    'success'
                                ).then(function () {
                                    location.reload();
                                });
                            },
                            400: function () {
                                Swal.fire(
                                    'Error!',
                                    'Bad request',
                                    'error'
                                ).then(function () {
                                    location.reload();
                                });
                            },
                            404: function () {
                                Swal.fire(
                                    'Error!',
                                    'Pagina no encontrada',
                                    'error'
                                ).then(function () {
                                    location.reload();
                                });
                            },
                            500: function () {
                                Swal.fire(
                                    'Error!',
                                    'Lo sentimos, hubo un error. Por favor intentelo de nuevo mas tarde',
                                    'error'
                                ).then(function () {
                                    location.reload();
                                });
                            }
                        }

                    });
                }
            })
        }
    </script>
}