ProyectoFinal/FrontEnd/Controllers/Admin/PromocionesAdminController.cs
using BackEnd.DAL;
using BackEnd.Entities;
using FrontEnd.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FrontEnd.Controllers.Admin
{
    [CustomAuthorize(Roles = "Admin")]
    public class PromocionesAdminController : Controller
    {

        UnidadDeTrabajo<promociones> unidad_promocion = new UnidadDeTrabajo<promociones>(new BDContext());
        UnidadDeTrabajo<estados> unidad_estados = new UnidadDeTrabajo<estados>(new BDContext());

        // GET: PromocionesAdmin
        public ActionResult Index()
        {
   
            List<promociones> promociones = unidad_promocion.genericDAL.GetAll().ToList();
            List<estados> estadoBD = unidad_estados.genericDAL.GetAll().ToList();

            List<PromocionesViewModel> promocionesVM = new List<PromocionesViewModel>();
            PromocionesViewModel promocionVM;

            foreach (var promocion in promociones)
            {
                if (promocion.id_estado == 1)
                {
                    continue;
                }
                else
                {
                    promocionVM = new PromocionesViewModel
                    {
                        promocionId = promocion.promocionId,
                        nombre = promocion.nombre, 
                        descripcion = promocion.descripcion,
                        valor = promocion.valor
                    };
                    promocionesVM.Add(promocionVM);
                }
            }
            return View("~/Views/Admin/PromocionesAdmin/Index.cshtml", promocionesVM);
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            PromocionesViewModel promocionVM = new PromocionesViewModel();
            return View("~/Views/Admin/PromocionesAdmin/Create.cshtml", promocionVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PromocionesViewModel promocionVM)
        {
            try
            {
                // TODO: Add insert logic here
                promociones promocion = new promociones
                {
                    nombre = promocionVM.nombre,
                    descripcion = promocionVM.descripcion,
                    valor = promocionVM.valor,
                    id_estado = 2
                };

                using (UnidadDeTrabajo<promociones> unidad = new UnidadDeTrabajo<promociones>(new BDContext()))
                {
                    unidad.genericDAL.Add(promocion);
                    unidad.Complete();
                }

                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        public ActionResult Edit(int id)
        {
            // revisar si el URL contiene un ID, si no entonces devolver 404
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            PromocionesViewModel promocionesViewModel;
            promociones promocion;

           

            using (UnidadDeTrabajo<promociones> unidad = new UnidadDeTrabajo<promociones>(new BDContext()))
            {
                promocion = unidad.genericDAL.Get(id);
            }

            // ver si el producto tiene estado bloqueado. Si si, devolver 404
            if (promocion.id_estado == 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            promocionesViewModel = new PromocionesViewModel
            {
                promocionId = promocion.promocionId,
                nombre = promocion.nombre,
                descripcion = promocion.descripcion,
                valor = promocion.valor,
                id_estado = 2
                
            };

            return View("~/Views/Admin/PromocionesAdmin/Edit.cshtml", promocionesViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PromocionesViewModel promocionesViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    promociones promocion = new promociones
                    {
                        promocionId = promocionesViewModel.promocionId,
                        nombre = promocionesViewModel.nombre,
                        descripcion = promocionesViewModel.descripcion,
                        valor = promocionesViewModel.valor,
                        id_estado = 2
                    };

                    using (UnidadDeTrabajo<promociones> unidad = new UnidadDeTrabajo<promociones>(new BDContext()))
                    {
                        unidad.genericDAL.Update(promocion);
                        unidad.Complete();
                        return new HttpStatusCodeResult(HttpStatusCode.OK);
                    }
                   
                }

                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
            catch (DataException /* dex */ )
            {
                // devolver error 500
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }
        
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                // revisar si el URL contiene un ID, si no entonces devolver 404
                if (id == 0)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                promociones promocion;
                using (UnidadDeTrabajo<promociones> unidad = new UnidadDeTrabajo<promociones>(new BDContext()))
                {

                    promocion = unidad.genericDAL.Get(id);
                    promocion.id_estado = 1;
                }

                using (UnidadDeTrabajo<promociones> unidad = new UnidadDeTrabajo<promociones>(new BDContext()))
                {

                    unidad.genericDAL.Update(promocion);
                    unidad.Complete();
                }

                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            catch
            {
              return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
    }
        }
    }
}

ProyectoFinal/FrontEnd/Views/Admin/PromocionesAdmin/Create.cshtml
@model FrontEnd.Models.PromocionesViewModel

@{
    ViewBag.Title = "Create";
}

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Agregar Promocion</h3>
    </div>
    <div class="box-body">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <form id="__AjaxAntiForgeryForm" action="#" method="post"> @Html.AntiForgeryToken()</form>
        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.valor, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.valor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.valor, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.ActionLink("Volver", "Index", routeValues: null, htmlAttributes: new { @class = "btn btn-primary" })
            <button type="submit" class="btn btn-primary" id="Guardar" onclick="guardar()">Guardar</button>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        function guardar() {
            var saveUrl = '@Url.Action("Create", "PromocionesAdmin")';
            var newUrl = '@Url.Action("Index", "PromocionesAdmin")';
            $.ajax({
                type: 'POST',
                url: saveUrl,
                data: {
                    __RequestVerificationToken: $('[name = "__RequestVerificationToken"]').val(),
                    nombre: $("#nombre").val(),
                    descripcion: $("#descripcion").val(),
                    valor: $("#valor").val(),
                },
                statusCode: {
                    200: function () {
                        Swal.fire(
                            'Promocion agregado!',
                            'La promocion ha sido agregado exitosamente!',
                            'success'
                        ).then(function () {
                            window.location.href = newUrl;
                        });
                    },
                    400: function () {
                        Swal.fire(
                            'Error!',
                            'Bad request',
                            'error'
                        ).then(function () {
                            location.reload();
                        });
                    },
                    404: function () {
                        Swal.fire(
                            'Error!',
                            'Pagina no encontrada',
                            'error'
                        ).then(function () {
                            location.reload();
                        });
                    },
                    500: function () {
                        Swal.fire(
                            'Error!',
                            'Lo sentimos, hubo un error. Por favor intentelo de nuevo mas tarde',
                            'error'
                        ).then(function () {
                            location.reload();
                        });
                    }
                }

            });
        }
    </script>
}

ProyectoFinal/FrontEnd/Views/Admin/PromocionesAdmin/Delete.cshtml
@model FrontEnd.Models.PromocionesViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Eliminar Promociones</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.valor)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProyectoFinal/FrontEnd/Views/Admin/PromocionesAdmin/Edit.cshtml
@model FrontEnd.Models.PromocionesViewModel

@{

    ViewBag.Title = "Actualizar Promocion";

}

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Actualizar Promocion</h3>
    </div>

    <div class="box-body">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <form id="__AjaxAntiForgeryForm" action="#" method="post"> @Html.AntiForgeryToken()</form>
        @Html.HiddenFor(model => model.promocionId)

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.valor, htmlAttributes: new { @class = "control-label " })
            @Html.EditorFor(model => model.valor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.valor, "", new { @class = "text-danger" })

        </div>

        <!-- /.box-body -->
        <div class="box-footer">
            @Html.ActionLink("Regresar", "Index")
            <button type="submit" class="btn btn-info pull-right" id="Guardar" onclick="guardar()">Editar</button>
        </div>
    </div>
</div>


@section Scripts
{
    <script>
        function guardar() {
            var saveUrl = '@Url.Action("Edit", "PromocionesAdmin")';
            var newUrl = '@Url.Action("Index", "PromocionesAdmin")';
            $.ajax({
                type: 'POST',
                url: saveUrl,
                data: {
                    __RequestVerificationToken: $('[name = "__RequestVerificationToken"]').val(),
                    promocionId: $("#promocionId").val(),
                    nombre: $("#nombre").val(),
                    descripcion: $("#descripcion").val(),
                    valor: $("#valor").val(),
                },
                statusCode: {
                    200: function () {
                        Swal.fire(
                            'Promocion editado!',
                            'La Promocion ha sido editado exitosamente!',
                            'success'
                        )
                        setTimeout(function () {
                            window.location.href = newUrl;
                        });

                    },
                    400: function () {
                        Swal.fire(
                            'Error!',
                            'Bad request',
                            'error'
                        )
                        setTimeout(function () {
                            location.reload();
                        });

                    },
                    404: function () {
                        Swal.fire(
                            'Error!',
                            'Pagina no encontrada',
                            'error'
                        )
                        setTimeout(function () {
                            location.reload();
                        });
                    },
                    500: function () {
                        Swal.fire(
                            'Error!',
                            'Lo sentimos, hubo un error. Por favor intentelo de nuevo mas tarde',
                            'error'
                        )
                        setTimeout(function () {
                            location.reload();
                        });
                    }
                }

            });
        }
    </script>
}

ProyectoFinal/FrontEnd/Views/Admin/PromocionesAdmin/Index.cshtml
@model IEnumerable<FrontEnd.Models.PromocionesViewModel>

@{
    ViewBag.Title = "Index";

}

@Html.Raw(Session["mensaje"])
<div class="btn-group">
    @Html.ActionLink("Agregar Nueva Promocion", "Create", null, new { @class = "btn btn-block btn-success" })
    <br><br><br>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="box">

            <div class="box-header">
                <h2 class="box-title">Promociones</h2>
            </div>

            <div class="box-body table-responsive">
                <table id="tablaPromociones" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.promocionId)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.nombre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.descripcion)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.valor)
                            </th>
                            <th>Acciones</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.promocionId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.descripcion)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.valor)
                                </td>
                                <td>
                                    @Html.ActionLink("Editar", "Edit", new { id = item.promocionId }, new { @class = "btn btn-warning" })
                                    <button type="button" class="btn btn-danger" onclick="eliminar(@item.promocionId)">Eliminar</button>
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>
            </div>
        </div>

    </div>
</div>


@section Scripts
{
    <script>
        $(document).ready(function () {
            cargarTabla();
        });

        // funcion para cargar DataTable con información de historial
        var cargarTabla = function () {
            var tabla = $("#tablaPromociones").DataTable({
                responsive: true,
                "destroy": true,
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                }
            });
        }

        function eliminar(id_promocion) {
            Swal.fire({
                title: 'Seguro que desea eliminar esta promoción?',
                text: "Esta accion no se puede revertir!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Eliminar'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: 'POST',
                        url: `PromocionesAdmin/Delete/${id_promocion}`,
                        data: {
                            id_categoria: id_promocion
                        },
                        statusCode: {
                            200: function () {
                                Swal.fire(
                                    'Exito!',
                                    'Promocion eliminada',
                                    'success'
                                ).then(function () {
                                    location.reload();
                                });
                            },
                            400: function () {
                                Swal.fire(
                                    'Error!',
                                    'Bad request',
                                    'error'
                                ).then(function () {
                                    location.reload();
                                });
                            },
                            404: function () {
                                Swal.fire(
                                    'Error!',
                                    'Pagina no encontrada',
                                    'error'
                                ).then(function () {
                                    location.reload();
                                });
                            },
                            500: function () {
                                Swal.fire(
                                    'Error!',
                                    'Lo sentimos, hubo un error. Por favor intentelo de nuevo mas tarde',
                                    'error'
                                ).then(function () {
                                    location.reload();
                                });
                            }
                        }

                    });
                }
            })
        }
    </script>
}